# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.head = QtWidgets.QFrame(self.frame)
        self.head.setMinimumSize(QtCore.QSize(0, 42))
        self.head.setStyleSheet("QFrame{\n"
"background-color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: #000000ff;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(222,222,222);\n"
"border-radius:20px;\n"
"}")
        self.head.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.head.setFrameShadow(QtWidgets.QFrame.Raised)
        self.head.setObjectName("head")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.head)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(571, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_min = QtWidgets.QPushButton(self.head)
        self.bt_min.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_min.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagenes/min3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_min.setIcon(icon)
        self.bt_min.setIconSize(QtCore.QSize(20, 20))
        self.bt_min.setObjectName("bt_min")
        self.horizontalLayout.addWidget(self.bt_min)
        self.bt_cont = QtWidgets.QPushButton(self.head)
        self.bt_cont.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_cont.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagenes/cont.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cont.setIcon(icon1)
        self.bt_cont.setIconSize(QtCore.QSize(20, 20))
        self.bt_cont.setObjectName("bt_cont")
        self.horizontalLayout.addWidget(self.bt_cont)
        self.bt_exp = QtWidgets.QPushButton(self.head)
        self.bt_exp.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_exp.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagenes/exp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_exp.setIcon(icon2)
        self.bt_exp.setIconSize(QtCore.QSize(20, 20))
        self.bt_exp.setObjectName("bt_exp")
        self.horizontalLayout.addWidget(self.bt_exp)
        self.bt_cerrar = QtWidgets.QPushButton(self.head)
        self.bt_cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imagenes/x-cf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cerrar.setIcon(icon3)
        self.bt_cerrar.setIconSize(QtCore.QSize(20, 20))
        self.bt_cerrar.setObjectName("bt_cerrar")
        self.horizontalLayout.addWidget(self.bt_cerrar)
        self.verticalLayout_2.addWidget(self.head)
        self.body = QtWidgets.QFrame(self.frame)
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.body)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_filtro = QtWidgets.QFrame(self.body)
        self.frame_filtro.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_filtro.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_filtro.setStyleSheet("QFrame {\n"
"    background-color: rgb(255,255,255);\n"
"    border-radius: 15px; /* Para esquinas redondeadas */\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(222,222,222); /* Color inicial del botón */\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    color: rgb(61,61,61); /* Texto oscuro */\n"
"    font: 22 10pt \"Arial Black\"; /* Fuente corregida (font en lugar de front) */\n"
"    border-radius: 15px; /* Para esquinas redondeadas */\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(200,200,200); /* Color ligeramente más oscuro al pasar el mouse */\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    color: rgb(61,61,61); /* Mismo color de texto */\n"
"    font: 22 10pt \"Arial Black\";\n"
"    border-radius: 15px; /* Para esquinas redondeadas */\n"
"\n"
"}\n"
"")
        self.frame_filtro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_filtro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_filtro.setObjectName("frame_filtro")
        self.bt_view = QtWidgets.QPushButton(self.frame_filtro)
        self.bt_view.setGeometry(QtCore.QRect(50, 10, 141, 31))
        self.bt_view.setObjectName("bt_view")
        self.bt_ejecutar = QtWidgets.QPushButton(self.frame_filtro)
        self.bt_ejecutar.setGeometry(QtCore.QRect(120, 470, 120, 30))
        self.bt_ejecutar.setMinimumSize(QtCore.QSize(120, 30))
        self.bt_ejecutar.setObjectName("bt_ejecutar")
        self.bt_limpiar = QtWidgets.QPushButton(self.frame_filtro)
        self.bt_limpiar.setGeometry(QtCore.QRect(10, 350, 120, 30))
        self.bt_limpiar.setMinimumSize(QtCore.QSize(120, 30))
        self.bt_limpiar.setObjectName("bt_limpiar")
        self.horizontalLayout_2.addWidget(self.frame_filtro)
        self.frame_res = QtWidgets.QFrame(self.body)
        self.frame_res.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_res.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_res.setObjectName("frame_res")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_res)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_res)
        self.stackedWidget.setStyleSheet("QFrame {\n"
"    background-color: rgb(61,61,61); /* Fondo gris oscuro */\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 87 12pt \"Arial Black\"; /* Fuente gruesa y tamaño moderado */\n"
"    background-color: transparent; /* Fondo transparente */\n"
"    color: rgb(0,0,0); /* Texto oscuro */\n"
"    border: 0px; /* Sin bordes */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 0px; /* Sin borde externo */\n"
"    color: rgb(255,255,255); /* Texto blanco */\n"
"    border-bottom: 2px solid rgb(61,61,61); /* Línea inferior en gris oscuro */\n"
"    font: 75 12pt \"Times New Roman\"; /* Fuente clásica */\n"
"    background-color: transparent; /* Fondo transparente */\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(222,222,222); /* Color inicial del botón */\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    color: rgb(61,61,61); /* Texto oscuro */\n"
"    font: 22 10pt \"Arial Black\"; /* Fuente corregida */\n"
"    border-radius: 15px; /* Esquinas redondeadas */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(200,200,200); /* Color ligeramente más oscuro al pasar el mouse */\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    color: rgb(61,61,61); /* Mismo color de texto */\n"
"    font: 22 10pt \"Arial Black\";\n"
"    border-radius: 15px; /* Esquinas redondeadas */\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: rgb(255,255,255); /* Fondo blanco */\n"
"    color: rgb(0,0,0); /* Texto negro */\n"
"    gridline-color: rgb(0,0,0); /* Color de líneas de la cuadrícula */\n"
"    font-size: 12pt;\n"
"    border: 0px; /* Sin borde */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(222,222,222); /* Fondo verde brillante */\n"
"    border: 0px; /* Sin borde */\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: rgb(200,200,200); /* Fondo gris oscuro */\n"
"    border: 0px; /* Sin borde */\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.view = QtWidgets.QWidget()
        self.view.setObjectName("view")
        self.gridLayout = QtWidgets.QGridLayout(self.view)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.view)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.bt_regresar = QtWidgets.QPushButton(self.view)
        self.bt_regresar.setMinimumSize(QtCore.QSize(120, 30))
        self.bt_regresar.setObjectName("bt_regresar")
        self.gridLayout.addWidget(self.bt_regresar, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(351, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.tabla_datos = QtWidgets.QTableWidget(self.view)
        self.tabla_datos.setObjectName("tabla_datos")
        self.tabla_datos.setColumnCount(0)
        self.tabla_datos.setRowCount(0)
        self.gridLayout.addWidget(self.tabla_datos, 1, 0, 1, 2)
        self.stackedWidget.addWidget(self.view)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_res)
        self.verticalLayout_2.addWidget(self.body)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_view.setText(_translate("MainWindow", "View Data"))
        self.bt_ejecutar.setText(_translate("MainWindow", "Ejecutar"))
        self.bt_limpiar.setText(_translate("MainWindow", "Limpiar"))
        self.label.setText(_translate("MainWindow", "DATOS"))
        self.bt_regresar.setText(_translate("MainWindow", "Regresar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
